### PR TITLE
(Re)use Client.HTTPClient for range requests

### LINKED ISSUE #126: Concurrent Image Download Ignores Configured HTTP Client
A user can optionally specify a custom `http.Client` by setting it in the `Config` passed to `NewClient`:

https://github.com/sylabs/scs-library-client/blob/5c8e366d610e8f705e9d85c1f72217e074deedda/client/client.go#L18-L30

There are two places I can see where we are not using this `http.Client`, where we probably should be.

The first is `httpGetRangeRequest`, which should be pretty straight forward:

https://github.com/sylabs/scs-library-client/blob/5c8e366d610e8f705e9d85c1f72217e074deedda/client/pull.go#L114

The second is `ConcurrentDownloadImage`, which overrides `CheckRedirect` in an otherwise zero-value `http.Client`:

https://github.com/sylabs/scs-library-client/blob/5c8e366d610e8f705e9d85c1f72217e074deedda/client/pull.go#L252-L256

In both cases, I think we should endeavour to use the user-supplied `http.Client` values, with the exception of overriding `CheckRedirect` in `ConcurrentDownloadImage`.

### LINKED ISSUE #142: Authorization header not set for multi-part download
`httpGetRangeRequest()` uses a generic HTTP client which does include a `Authorization` header:

https://github.com/sylabs/scs-library-client/blob/eeab0e8dd3a70c3b0d448e7fc0768db67b3646ad/client/pull.go#L106-L114

This causes a 401 Unauthorized error when attempting to access private projects (which require authorization) in Sylabs Cloud Library.

### PR DESCRIPTION
**Pull request by EmmEff**
Also sets `Authorization` header, required for accessing private Sylabs Cloud projects.

Closes #142 , closes #126

### CODE REVIEW

File: client/pull.go [hunk 1]
```diff
@@ -103,20 +103,24 @@ type Downloader struct {
...
 	}
 
 	req.Header.Add("Range", fmt.Sprintf("bytes=%d-%d", start, end))
 
-	return http.DefaultClient.Do(req)
+	if c.AuthToken != "" {
+		req.Header.Add("Authorization", fmt.Sprintf("BEARER %v", c.AuthToken))
+	}
+
+	return c.HTTPClient.Do(req)
```
Comment (tri-adam) [inline client/pull.go:118]: We should probably use `(*Client).newRequest` rather than `http.NewRequestWithContext` above, which will set the `Authorization` and also the `User-Agent`.

With that, I believe this can be simplified to:

```suggestion
	return c.HTTPClient.Do(req.WithContext(ctx))
```

**Review by tri-adam — CHANGES_REQUESTED** [review]

File: client/pull.go (hunk 1 above)
Comment (EmmEff) [reply client/pull.go]: I hope I didn't overdo it :)

File: client/client.go [hunk 2]
```diff
@@ -97,14 +98,66 @@ func NewClient(cfg *Config) (*Client, error) {
...
+
 // newRequest returns a new Request given a method, path (relative or
 // absolute), rawQuery, and (optional) body.
-func (c *Client) newRequest(method, path, rawQuery string, body io.Reader) (*http.Request, error) {
-	u := c.BaseURL.ResolveReference(&url.URL{
-		Path:     path,
-		RawQuery: rawQuery,
-	})
-	r, err := http.NewRequest(method, u.String(), body)
+func (c *Client) newRequest(ctx context.Context, method string, opts ...newRequestOptFunc) (*http.Request, error) {
```
Comment (tri-adam) [inline client/client.go:144]: If we're going to diverge further from [http.NewRequestWithContext](https://pkg.go.dev/net/http#NewRequestWithContext), it would be nice to explicitly call out what the options are to set the `path` and `body`.

File: client/client.go [hunk 3]
```diff
@@ -97,14 +98,66 @@ func NewClient(cfg *Config) (*Client, error) {
...
+	}
+
+	var u *url.URL
+	if o.absURI == nil {
+		u = c.BaseURL.ResolveReference(&url.URL{
+			Path:     o.refPath,
+			RawQuery: o.rawQuery,
+		})
+	} else {
+		u = o.absURI
```
Comment (tri-adam) [inline client/client.go:157]: What should happen when both `newRequestOptAbsoluteURI` and `newRequestOptQuery` are provided? The caller seems to have two options to set a query parameter, but only one of them will work as expected I think?

**Review by tri-adam — COMMENTED** [review]
This adds quite a bit of complexity, and some edge cases around combination of options.

Reading between the lines, the added functionality here is the ability to set an absolute URL? If so, I wonder if it might be simpler for maintenance to simply add a new function with the same signature as [http.NewRequestWithContext](https://pkg.go.dev/net/http#NewRequestWithContext):

```go
func (c *Client) newRequestWithURL(ctx, method, url string, body io.Reader) (*http.Request, error)
```

The existing function could then stay in place:

```go
func (c *Client) newRequest(ctx, method, path, rawQuery string, body io.Reader) (*http.Request, error)
```

And all `newRequest` would need to do is use `c.BaseURL.ResolveReference` to assemble a `url`, and call `newRequestWithURL` which would house the logic to set the `Authorization` and `User-Agent` headers.

**Review by tri-adam — APPROVED** [review]
